
kind: pipeline
name: slickLab

environment:
  repo: https://github.com/LineageOs/android
  branch: lineage-17.1
  depis: ginkgo
  hals: y
  dhal: 2
  depis: ginkgo
  lun: lunch lineage_ginkgo-userdebug
  type: userdebug
  comp: brunch ginkgo
  compile: brunch ginkgo
  setup: bash envsetup/build.sh
  rom: lineage
steps:
- name: tes
  image: fr3akyphantom/droid-builder:latest
  environment:
    BOT_TOKEN:
      from_secret: BOT_TOKEN
  commands:
  - wget https://raw.githubusercontent.com/rzlamrr/scripts/master/sync.sh
  - chmod +x sync.sh
  - bash sync.sh
  steps:
- name: tos
  image: fr3akyphantom/droid-builder:latest
  environment:
    BOT_TOKEN:
      from_secret: BOT_TOKEN
  commands:
  - wget https://raw.githubusercontent.com/rzlamrr/scripts/master/build.sh
  - chmod +x build.sh
  - bash build.sh
